version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/add_to_app/my_flutter_module"
    schedule:
      interval: "weekly"


  - package-ecosystem: "pub"
    directory: "/flavors"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/multi_dimensional_flavors"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/progressive_rollout_demo"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/shorebird_fintech_wallet"
    schedule:
      interval: "weekly"
