name: multi_dimensioanl_flavors
description: A Shorebird app which contains multiple, multi dimensional flavors on Android.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  assets:
    - shorebird.yaml
  uses-material-design: true
